#!/bin/bash
# #This line makes my answers blue
	blue=`tput setaf 4`
# #This line makes my answers yellow
	yellow=`tput setaf 3`
# #This line makes my answers green
	green=`tput setaf 2`
# #This line makes my answers red
	red=`tput setaf 1`
# #This line reset thew collow
	reset=`tput sgr0`


while true 
do
	clear
	echo "${blue}####### RHCSA MACHINE #######"
	echo "1. Add User for RHCSA"
	echo "${yellow}2. Just kill username form system"
	echo "${red}3. Delete User from system"
	read -p "${blue}Enter the options :${reset}" ANSWER

	if [ $ANSWER == "1" ]
	then
		read -p "${green}Enter the USERs name :${reset}" USER 
		read -p "${green}Enter the passwd for USER :${reset}" passwd 
		useradd -G libvirt $USER
		echo $passwd |passwd --stdin $USER
		mkdir /home/$USER/Desktop -p
		cp -p /root/Desktop/Tasks.txt /home/$USER/Desktop/ 
		virsh snapshot-revert RHCSA ORIGINAL
		virsh snapshot-create-as RHCSA $USER
		virsh start "Don't_touch" 2>/dev/null
		break
	elif [ $ANSWER == "2" ]
	then
		USERS=$( cat /etc/passwd | awk -F ':' ' $4 > 1000{print }' | awk -F ':' '{print $1}')
		echo $USERS
		read -p "${red}Enter the usersname :${reset}" USER 
		CHECK=$(cat /etc/passwd | grep -o $USER | head -n1)
		if [[ $USER == $CHECK ]]
		then  
			pkill -u $USER 
			usermod -s /sbin/nologin  $USER 
			virsh reboot RHCSA
			break
		else	
			echo "${yellow}The username $USER doesn't exist"
			sleep 1
		fi
	elif [ $ANSWER == "3" ]
	then
		read -p "${red}Are you sure ?${reset}" ANSWER
		if [[ $ANSWER == [y/Y] ]]
		then
			USERS=$( cat /etc/passwd | awk -F ':' ' $4 > 1000{print }' | awk -F ':' '{print $1}')
			echo $USERS
			read -p "${red}Enter the usersname :${reset}" USER 
			CHECK=$(cat /etc/passwd | grep -o $USER | head -n1)
			if [ $USER == "ansible" ]
			then
				echo "Sorry you can't delete ansible user"
				sleep 2
			elif [[ $USER == $CHECK ]]
			then  
				pkill -u $USER 
				userdel -r  $USER 
				virsh snapshot-revert RHCSA ORIGINAL
				virsh snapshot-delete RHCSA $USER
			else	
				echo "${yellow}The username $USER doesn't exist"
				sleep 1
			fi
		else
			break
		fi
	else 
		echo "${yellow}You chosed wrong options"
		sleep 1
	fi
done


